### ISSUE TITLE
Energy on Electrode

### ISSUE THREAD

**Issue by LucasCotrim-dev** [InertSteak/Pokermon#13]
When energy (either colorless or electric) is used on electrode the game crashes. Latest version of the mod. I was using unlimited energy config, but turning it off didnt seem to fix it either.
Crash log below
[crashLog.txt](https://github.com/user-attachments/files/17403605/crashLog.txt)

**Comment by InertSteak** [comment]
Thanks for the report, I had not properly updated an internal array which results in the crash. I have made a new small release as this is a fairly big issue.
