### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LegacyTriforce** [InertSteak/Pokermon#14]
[https://drive.google.com/file/d/1lqR-_oK6tqEz837rp5gGEOMrtI9VI9lW/view?usp=drive_link](url) 

Link contains the crash log and 2 images showing what happened.

**Comment by InertSteak** [comment]
Known issue, fixed in release 1.6.1. Could you please try that version and let me know if you run into the crash?

**Comment by LegacyTriforce** [comment]
I have updated to the current version, and it does seem to be fixed. It allowed me to continue without the crash.

**Comment by LegacyTriforce** [comment]
Sorry, I recently just updated to 1.6.1 and it does seemed to be fixed!

**Comment by InertSteak** [comment]
No worries. Glad it's working for you now! Thanks for the report
