### ISSUE TITLE
Crash with Colorless Energy

### ISSUE THREAD

**Issue by TheLemon27** [InertSteak/Pokermon#16]
I was playing a crazy run and when I used a Colorless energy from the shop, the game crashed and gave me the following crash message. Below is the crash message and 2 screenshots, one normal, and one with the leftmost joker highlighted.

![20241017184851_1](https://github.com/user-attachments/assets/856bc624-bdb1-4a74-b7b3-7c965ba428cc)
![20241017184859_1](https://github.com/user-attachments/assets/c3fc8728-920c-48e1-a011-53721ce5badf)

`Oops! The game crashed:
[SMODS Pokermon "pokefunctions.lua"]:76: attempt to perform arithmetic on local 'addition' (a nil value)

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-0927a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta7
Steamodded Mods:
    1: Archipelago Randomizer by Burndi, SpaD_Overolls, Myst, Silvris [ID: Rando, Version: 0.1.9]
    2: Cryptid by MathIsFun_, Cryptid and Balatro Discords [ID: Cryptid, Priority: 1e+299, Version: 0.5.1, Uses Lovely]
    3: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta8, Uses Lovely]
        Break Infinity: omeganum
    4: Pokermon by See Credits Tab [ID: Pokermon, Version: 1.6.0, Uses Lovely]
    5: Happy Birthday! [indev] by TheLemon27 [ID: BirthdayCardMod_indev]
    6: More Fluff by notmario [ID: MoreFluff, Version: 1.0.1d, Uses Lovely]
    7: Grim by mathguy [ID: GRM, Version: 0.9.4, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua global 'energize' at file 'pokefunctions.lua:76' (from mod with id Pokermon)
Local variables:
 card = table: 0x20b860a8  {click_offset:table: 0x2156d200, children:table: 0x216c01e8, ambient_tilt:0.2 (more...)}
 etype = string: "Colorless"
 evolving = boolean: false
 (for generator) = C function: next
 (for state) = table: 0x24268778  {ptype:Grass, odds:20, c_energy_count:1, chips:33, money:1.4, mult:3.2}
 (for control) = number: nan
 l = string: "money"
 data = number: 1.4
 (for generator) = C function: builtin#6
 (for state) = table: 0x20bec578  {1:mult, 2:mult1, 3:mult2, 4:chips, 5:chips1, 6:chips2, 7:Xmult, 8:money (more...)}
 (for control) = number: 8
 m = number: 8
 name = string: "money"
 addition = nil
 (*temporary) = table: 0x24268778  {ptype:Grass, odds:20, c_energy_count:1, chips:33, money:1.4, mult:3.2}
 (*temporary) = number: 33
 (*temporary) = table: 0x24574fb0  {}
 (*temporary) = string: "attempt to perform arithmetic on local 'addition' (a nil value)"
(4) Lua method 'use' at file 'pokefunctions.lua:287' (from mod with id Pokermon)
Local variables:
 self = table: 0x20fe34c8  {can_use:function: 0x20fe3640, loc_vars:function: 0x20fe35c0, _saved_d_u:true (more...)}
 card = table: 0x217f3250  {added_to_deck:true, highlighted:false, click_offset:table: 0x217f3640, last_moved:-1 (more...)}
 area = nil
 copier = nil
 applied = boolean: false
 (for generator) = C function: next
 (for state) = table: 0x21611078  {1:table: 0x216110c8, 2:table: 0x20e34000, 3:table: 0x20a0dff0, 4:table: 0x218a18d0 (more...)}
 (for control) = number: nan
 k = number: 26
 v = table: 0x20b860a8  {click_offset:table: 0x2156d200, children:table: 0x216c01e8, ambient_tilt:0.2 (more...)}
(5) Lua upvalue 'uc' at file 'card.lua:1400'
Local variables:
 self = table: 0x217f3250  {added_to_deck:true, highlighted:false, click_offset:table: 0x217f3640, last_moved:-1 (more...)}
 area = nil
 copier = nil
 used_tarot = table: 0x217f3250  {added_to_deck:true, highlighted:false, click_offset:table: 0x217f3640, last_moved:-1 (more...)}
 gone = boolean: false
 obj = table: 0x20fe34c8  {can_use:function: 0x20fe3640, loc_vars:function: 0x20fe35c0, _saved_d_u:true (more...)}
(6) Lua method 'use_consumeable' at file 'Cryptid.lua:501' (from mod with id Cryptid)
Local variables:
 self = table: 0x217f3250  {added_to_deck:true, highlighted:false, click_offset:table: 0x217f3640, last_moved:-1 (more...)}
 area = nil
 copier = nil
 ggpn = number: 2
(7) Lua field 'use_card' at file 'functions/button_callbacks.lua:2270'
Local variables:
 e = table: 0x22984e80  {pixellated_rect:table: 0x257833b0, click_offset:table: 0x20c58c78, children:table: 0x22984ea8 (more...)}
 mute = boolean: true
 nosave = nil
 card = table: 0x217f3250  {added_to_deck:true, highlighted:false, click_offset:table: 0x217f3640, last_moved:-1 (more...)}
 area = nil
 prev_state = number: 5
 dont_dissolve = nil
 delay_fac = number: 1
 nc = nil
(8) Lua field 'func' at file 'functions/button_callbacks.lua:2539'
(9) Lua method 'handle' at file 'engine/event.lua:55'
Local variables:
 self = table: 0x244aeb80  {start_timer:true, timer:TOTAL, blockable:true, trigger:after, func:function: 0x244aeb18 (more...)}
 _results = table: 0x211c8f18  {blocking:true, pause_skip:false, time_done:true, completed:false}
(10) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x20379a40  {queue_last_processed:358.2, queues:table: 0x20532948, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.0178033
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x20532948  {unlock:table: 0x204dc018, other:table: 0x2072c9a0, tutorial:table: 0x20456780 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x204dc040  {1:table: 0x20a341e0, 2:table: 0x244aeb80, 3:table: 0x24eee0c8, 4:table: 0x2457d0f8 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x211c8f18  {blocking:true, pause_skip:false, time_done:true, completed:false}
(11) Lua upvalue 'gameUpdateRef' at file 'game.lua:2757'
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
 http_resp = nil
(12) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(13) Lua upvalue 'game_updateref' at file 'main.lua:1719'
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(14) Lua upvalue 'game_updateRef' at file 'other/colours.lua:1022' (from mod with id MoreFluff)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(15) Lua upvalue 'upd' at file 'randomizer.lua:312' (from mod with id Rando)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(16) Lua upvalue 'upd' at file 'Items/Blinds.lua:1282' (from mod with id Cryptid)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(17) Lua upvalue 'upd' at file 'Items/CodeCards.lua:3724' (from mod with id Cryptid)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(18) Lua upvalue 'upd' at file 'Items/Decks.lua:359' (from mod with id Cryptid)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(19) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4805' (from mod with id Cryptid)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(20) Lua method 'update' at file 'Cryptid.lua:2514' (from mod with id Cryptid)
Local variables:
 self = table: 0x2046cef0  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x218f60e0 (more...)}
 dt = number: 0.0178033
(21) Lua field 'update' at file 'main.lua:970'
Local variables:
 dt = number: 0.0178033
(22) Lua function '?' at file 'main.lua:909' (best guess)
(23) global C function 'xpcall'
(24) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 880 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])`

**Comment by TheLemon27** [comment]
just checked, it seemingly happens with every energy card

**Comment by InertSteak** [comment]
Are you using version 1.6.1? This was a known issue that I fixed in version 1.6.0.

**Comment by TheLemon27** [comment]
nope! i think that was it, thanks!
(i'll reopen this issue if that wasn't it.)
