### ISSUE TITLE
Pokemon Jokers only doesnt work

### ISSUE THREAD

**Issue by TheBackslashKey** [InertSteak/Pokermon#17]
Hello,

I have the options for Pokemon only AND Jokers only, yet neither of them make it so only pokemon appear.

**Comment by InertSteak** [comment]
Which version of the mod are you using?

**Comment by TheBackslashKey** [comment]
The latest as far as I am aware. I downloaded the zip this morning lol. I may need to update steamodded or lovely since those have been on my pc for a few weeks now.

**Comment by InertSteak** [comment]
Yeah I would try updating those. The pokemon only setting relies on a config that might not be loading properly depending on your version of steamodded or lovely

**Comment by TheBackslashKey** [comment]
I figured out the issue! Step 3 in your installation process breaks it. You can extract the zip folder straight into your mods folder - you don't need to make your own Pokermon folder! 
Thank you though!!!

**Comment by InertSteak** [comment]
Ah I see, step 3 could be worded better. I'll update the readme soon. Glad it works!

**Comment by TheBackslashKey** [comment]
Also, would you mind letting me know what MissingNo does? It seemed to increase my hand size, and also change suits of cards… I took it from a master ball to see and it killed my run LOL

**Comment by InertSteak** [comment]
Yeah it scores mult, chips, xmult, money, changes suits and ranks of cards and increases and decreases hand size at random. It also will copy the first consumable you have to every available space.
