### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by ApolloAzrael** [InertSteak/Pokermon#18]
Trying to use in tandem with Balatro - Hidden Aces mod. Error log is as follows: 

Oops! The game crashed:
Syntax error: game.lua:3579: 'end' expected (to close 'function' at line 1976) near '<eof>'

Additional Context:
Balatro Version: ???
Modded Version: ???
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6

Stack Traceback
===============
(3)  C function 'function: 0x3c54aeb0'
(4) global C function 'require'
(5) main chunk of file 'main.lua' at line 850
(6) global C function 'require'
(7) Love2D function at file 'boot.lua:323' (best guess)
Local variables:
 c = table: 0x3c54d8c8  {identity:false, version:11.5, accelerometerjoystick:true, modules:table: 0x3c54d918 (more...)}
 openedconsole = boolean: false
 confok = boolean: true
 conferr = nil
(8) global C function 'xpcall'
(9) Love2D function at file 'boot.lua:362' (best guess)
Local variables:
 result = boolean: true
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by InertSteak** [comment]
Do Pokermon and Hidden aces each work separately?

**Comment by ApolloAzrael** [comment]
If I remove lovely, Balatro boots as normal, but I can't confirm Pokermon works without reinstalling, which I'll do shortly.

**Comment by ApolloAzrael** [comment]
Pokermon boots standalone as well. Is it just one or the other?

**Comment by InertSteak** [comment]
Yeah this seems like a mod conflict. I know that can happen between steamodded and non steamodded mods. I'll keep this open to remind me its an issue, but I'm not sure if there's much I can do unfortunately
