### ISSUE TITLE
Jynx's type popup says its type is Water

### ISSUE THREAD

**Issue by RandomNerd1** [InertSteak/Pokermon#21]
I could tell it wasn't actually water in game (because I couldn't use a water energy when I had it and no water pokemon), and it has the correct type sticker on it, I think it was just labeled wrong in the overlay somehow.

**Comment by InertSteak** [comment]
Good catch, Jynx was incorrectly labeled as a water type. I've fixed it now. Fyi, energy cards aren't usable on Jynx as it has no scoring values. Thanks!

**Comment by RandomNerd1** [comment]
I won't uncomplete this obviously, but since I more or less have your attention:

1. Are there plans to indicate how many ( X/5 ) energy cards have been used on a Pokemon, on mouseover? Would be nice not to have to mentally keep track.

2. Maybe there is one and I just failed to notice it, but if not, are there plans to add some definitive indicator to Pokemon that can't have energy used on them? Having no scoring values helps one guess, but for example, I was a bit surprised to learn that Poliwag/Poliwhirl (can't confirm Poliwrath since I never found a water stone, lol) can't use water energy.

**Comment by InertSteak** [comment]
1. Thanks for reminding me, I had meant to add a counter earlier but didn't get around to it. 
2. That's probably a good idea at some point. I'll think on the implementation
