### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Tapas31000** [InertSteak/Pokermon#23]
![Capture d’écran 2024-10-23 202709](https://github.com/user-attachments/assets/c654bae2-b1a9-42af-99f8-dc0061a68141)

I have this issue when i launch the game

**Comment by InertSteak** [comment]
Hi, 
That error usually indicates an out of date lovely or steamodded version. Try updating those and try again.

**Comment by Tapas31000** [comment]
Hi 
I resolved the first error and now it chose me that
[Error.txt](https://github.com/user-attachments/files/17534640/Error.txt)

**Comment by InertSteak** [comment]
That is a very odd error. Are you sure you have lovely and steamodded installed correctly? Have you tried with any other mods?

**Comment by Tapas31000** [comment]
It works with other mods so I guess they are installed correctly

**Comment by failuer101** [comment]
I'm having the same issue as the original post

I have steammodded 0.9.8 and lovely v0.6.0

**Comment by failuer101** [comment]
Fixed. I needed the 1.0 alpha of steammodded

**Comment by liddefixe** [comment]
i have the same issue but i can't figure out where to find the  1.0 alpha of steammodded, where do i find it?
