### ISSUE TITLE
Energy and Tera Types don't work as expected

### ISSUE THREAD

**Issue by Drakiith** [InertSteak/Pokermon#24]
If you use Energy for a tera typed Pokémon, but you have another Pokémon with a tera type, whose base type is that Energy's type, it will apply to that instead.
e.g. Tera Psychic Starmie to the left, Tera Water Magmar to the right, using a Water energy will boost the Starmie rather than the Magmar
![starmie 2 energy](https://github.com/user-attachments/assets/d486ff4a-a7ff-495e-a38e-79f6b3e2b008)
![magmar 0 energy](https://github.com/user-attachments/assets/1adf41db-eeba-4caa-9e0d-8c1fca359b2c)
![starmie 3 energy](https://github.com/user-attachments/assets/f29a4f37-0ac2-4ec5-80e5-69a9054fe1e3)
![magmar still 0 energy](https://github.com/user-attachments/assets/d4fb3ba3-1d11-4e2d-819a-912daa1f10e7)

**Comment by InertSteak** [comment]
Hi, I'm not able to replicate this unfortunately. Could you try to get the latest code and let me know if it happens again?

**Comment by Drakiith** [comment]
That was the first run I had after I grabbed the code this morning, so that's odd. My only other mods are nopeus and talisman, I can't imagine they'd mess with it.
I'll try updating everything and I'll see if it happens again when I play next

**Comment by Drakiith** [comment]
Updated every mod and prereqs, got a dark drowzee and a psychic pinsir and it worked as expected this time.
I already think I had everything up to date, but I guess I didn't, or there's some very specific edge case causing it I suppose.

**Comment by InertSteak** [comment]
Yeah super odd, I tried with a few different setups but wasn't able to make it happen. I could see it being an edge case. If it happens again, let me know and I'll reopen this issue.

**Comment by Drakiith** [comment]
I just had a situation where I could use a steel energy on a Metang that had a dragon sticker on it - I wonder if it has anything to do with a Pokémon evolving while having a sticker? I think I used the Dragon Scale while it was still a Beldum.
I did _not_ however, have any other Pokémon that were Steel type, tera or not.

**Comment by Drakiith** [comment]
It does seem to be an issue with evolving. I don't think I did anything wrong installation wise.
![image](https://github.com/user-attachments/assets/8fb55e9b-681c-444b-93fc-4dccc1abdab8)
![image](https://github.com/user-attachments/assets/c61a3300-f362-4782-8dd8-49f6d1f71400)

**Comment by InertSteak** [comment]
Oh you know what, I know what it is now. I'll go fix that section of my code. I'm applying the type sticker on evolution but not changing the internal type.

**Comment by InertSteak** [comment]
Ok, I believe I've fixed this. Let me know if it happens again with the latest code
