### ISSUE TITLE
Only Pokemon options not working

### ISSUE THREAD

**Issue by Azyoko** [InertSteak/Pokermon#26]
![Screen1](https://github.com/user-attachments/assets/d785beb3-d9b0-4eac-ba34-209343720a96)
![Screen2](https://github.com/user-attachments/assets/2e42a894-48d2-47ee-ba29-7fc8fd15ca54)
![Screen3](https://github.com/user-attachments/assets/2f49dde4-0c34-40eb-8987-8230759ee73b)
Tried to restart balatro and my pc and nothing works :/

**Comment by InertSteak** [comment]
Usually this means the file structure is wrong. It should be
\Balatro\Mods\Pokermon and then the files on github, not \Balatro\Mods\Pokermon\Pokermon.

**Comment by InertSteak** [comment]
No worries, it's all good!
