### ISSUE TITLE
Negative playing cards reduce true hand size

### ISSUE THREAD

**Issue by failuer101** [InertSteak/Pokermon#27]
I don't know what causes it exactly but it slowly wittles down your hand size about every other round until you lose due to 0 hand size

**Comment by InertSteak** [comment]
Did you have a missingno? That can reduce hand size
Otherwise, negative playing cards doing that would be a steamodded issue, not specifically with pokermon.

**Comment by failuer101** [comment]
no missingno

**Comment by InertSteak** [comment]
Yeah my guess is a steamodded bug then. I didn't touch anything regarding negative playing cards.
