### ISSUE TITLE
Venomoth/nat bug with oops all sixes

### ISSUE THREAD

**Issue by failuer101** [InertSteak/Pokermon#29]
i picked up sixes first which doubled mews odds to 2 of 6 and then i picked up venonat which changed it to 3 of 6 but when I did it in the opposite order, venonat then sixes, it changed mews odds to 4 of 6. Further, when venonat evolved on this most recent run, mews odds went from 3 of 6 to 5 of 6. so i figured it was an order issue where since i picked up sixes first it doubles mews odds and then adds 3 but when i sold sixes to start looking for another, mews odds dropped to 2.5 of 6, halving the current odds of 5 of 6.

**Comment by InertSteak** [comment]
Forgot to circle back on this, this has been fixed now.
