### ISSUE TITLE
Game crashes on beating bosses?

### ISSUE THREAD

**Issue by seeker7r4c3r** [InertSteak/Pokermon#41]
Heres the crash log

Oops! The game crashed:
[SMODS Pokermon "pokefunctions.lua"]:69: attempt to perform arithmetic on local 'addition' (a nil value)

Additional Context:
Balatro Version: 1.0.1m-FULL
Modded Version: 1.0.0~ALPHA-1103a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Pokermon by See Credits Tab [ID: Pokermon, Version: 1.6.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua global 'energize' at file 'pokefunctions.lua:69' (from mod with id Pokermon)
Local variables:
 card = table: 0x20248028  {click_offset:table: 0x200a43f8, children:table: 0x1feb3c20, ambient_tilt:0.2 (more...)}
 etype = nil
 evolving = boolean: true
 (for generator) = C function: next
 (for state) = table: 0x1fd5a670  {Xmult:2, money_mod:2, mult_mod:4, chip_mod:40, ptype:Dark, money:0, Xmult_mod:0.2 (more...)}
 (for control) = number: nan
 l = string: "money_mod"
 data = number: 2
 (for generator) = C function: builtin#6
 (for state) = table: 0x20076838  {1:mult, 2:mult1, 3:mult2, 4:chips, 5:chips1, 6:chips2, 7:Xmult, 8:money (more...)}
 (for control) = number: 14
 m = number: 14
 name = string: "money_mod"
 addition = nil
 (*temporary) = number: 2
 (*temporary) = number: 2
 (*temporary) = number: 0
 (*temporary) = string: "attempt to perform arithmetic on local 'addition' (a nil value)"
(4) Lua global 'evolve' at file 'pokefunctions.lua:170' (from mod with id Pokermon)
Local variables:
 self = table: 0x202760a0  {alerted:false, loc_vars:function: 0x2004adf8, _saved_d_u:true, original_key:zubat (more...)}
 card = table: 0x201da4f8  {sticker_run:NONE, click_offset:table: 0x20217950, children:table: 0x1feaab68 (more...)}
 context = table: 0x200b9070  {end_of_round:true, callback:function: 0x1fef57d8, game_over:false}
 forced_key = string: "j_poke_golbat"
 previous_edition = table: 0x1ff46578  {type:foil, chips:50, foil:true, key:e_foil}
 previous_perishable = nil
 previous_eternal = nil
 previous_rental = nil
 previous_energy_count = number: 2
 previous_c_energy_count = nil
 new_card = table: 0x20248028  {click_offset:table: 0x200a43f8, children:table: 0x1feb3c20, ambient_tilt:0.2 (more...)}
(5) Lua method 'calculate' at file 'pokefunctions.lua:218' (from mod with id Pokermon)
Local variables:
 self = table: 0x202760a0  {alerted:false, loc_vars:function: 0x2004adf8, _saved_d_u:true, original_key:zubat (more...)}
 card = table: 0x201da4f8  {sticker_run:NONE, click_offset:table: 0x20217950, children:table: 0x1feaab68 (more...)}
 context = table: 0x200b9070  {end_of_round:true, callback:function: 0x1fef57d8, game_over:false}
 forced_key = string: "j_poke_golbat"
 current = number: 14
 target = number: 12
 (*temporary) = table: 0x2070ab70  {}
(6) Lua upvalue 'cj' at file 'card.lua:2428'
Local variables:
 self = table: 0x201da4f8  {sticker_run:NONE, click_offset:table: 0x20217950, children:table: 0x1feaab68 (more...)}
 context = table: 0x200b9070  {end_of_round:true, callback:function: 0x1fef57d8, game_over:false}
 obj = table: 0x202760a0  {alerted:false, loc_vars:function: 0x2004adf8, _saved_d_u:true, original_key:zubat (more...)}
(7) Lua method 'calculate_joker' at Steamodded file 'core/overrides.lua:2075' 
Local variables:
 self = table: 0x201da4f8  {sticker_run:NONE, click_offset:table: 0x20217950, children:table: 0x1feaab68 (more...)}
 context = table: 0x200b9070  {end_of_round:true, callback:function: 0x1fef57d8, game_over:false}
(8) Lua field 'func' at file 'functions/state_events.lua:104'
Local variables:
 game_over = boolean: false
 game_won = boolean: false
 (for index) = number: 3
 (for limit) = number: 5
 (for step) = number: 1
 i = number: 3
 eval = nil
(9) Lua method 'handle' at file 'engine/event.lua:55'
Local variables:
 self = table: 0x2063fae0  {start_timer:true, timer:TOTAL, blockable:true, trigger:after, func:function: 0x206c8ae0 (more...)}
 _results = table: 0x20303fc8  {blocking:true, pause_skip:false, time_done:true, completed:false}
(10) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x20305f50  {queue_last_processed:23.35, queues:table: 0x20305f78, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00417099
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x20305f78  {unlock:table: 0x20305fa0, other:table: 0x20306418, tutorial:table: 0x20305ff0 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x20305fc8  {1:table: 0x206541e8, 2:table: 0x2063fae0, 3:table: 0x1fe0fb40, 4:table: 0x1fdc9aa0 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x20303fc8  {blocking:true, pause_skip:false, time_done:true, completed:false}
(11) Lua upvalue 'gameUpdateRef' at file 'game.lua:2502'
Local variables:
 self = table: 0x1fcedf78  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x209459b8 (more...)}
 dt = number: 0.00417099
 http_resp = nil
(12) Lua method 'update' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x1fcedf78  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x209459b8 (more...)}
 dt = number: 0.00417099
(13) Lua field 'update' at file 'main.lua:965'
Local variables:
 dt = number: 0.00417099
(14) Lua function '?' at file 'main.lua:909' (best guess)
(15) global C function 'xpcall'
(16) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 880 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by InertSteak** [comment]
I think that was an issue in an older version. Try the newer version and see if its still broken

**Comment by seeker7r4c3r** [comment]
Ah yes, sorry i was using the latest from nexus.

**Comment by InertSteak** [comment]
Right, I haven't updated that in a while sorry. I'll 2.0.0 on there when I get the chance
