### ISSUE TITLE
Marowak instantly crashes game

### ISSUE THREAD

**Issue by Raaace** [InertSteak/Pokermon#51]
Every time I mouse over Marowak it instantly crashes the game with this dialogue:

[SMODS Pokermon "pokemon/pokejokers_4.lua"]:524: attempt to index field 'consumeables' [a nil value]

I'm assuming this indicates that "consumeables" is a typo somewhere in the files related to this card but I have no clue how to fix this myself.

**Comment by Raaace** [comment]
I tried going under Marowak's scripts in the relevant text file and changing the six relevant fields to read "consumable" instead, that obviously didn't work.
I see now in the script text files that "consumeables" is indeed used as a field for multiple pokejokers. So idk wtf is going on

**Comment by InertSteak** [comment]
Yeah so confusingly enough, "consumeables" is the spelling Balatro uses for that area. 

As for the bug, I verified and fix the issue. I wasn't properly checking the existence of consumeables before indexing it. It will be fixed in my next check in
