### ISSUE TITLE
Pidgey/Pidgeotto/Pidgeot Not Reducing Price of Celestial Packs/Cards

### ISSUE THREAD

**Issue by scotthbk** [InertSteak/Pokermon#55]
Hi, first of all, I would like to say what a fantastic job you have done with this mod, it is truly astounding!

I'm very new to the modding scene so please forgive me if this has already been raised or has been dealt with.

I believe that as stated in the title, the Pidgey family of jokers do not appear to reduce the price of Planet Cards nor celestial packs.

**Comment by InertSteak** [comment]
Thanks! Glad you're enjoying it! 
So you're not the first to report this and it typically indicates one of two things. 
1. More likely, your lovely version is outdated. With version 6.0.0 of Lovely they added better pattern matching which Pidgey makes use of. 
2. Less likely but possible, your folder setup is nested which breaks some things. It should look like Balatro\Mods\Pokermon and not Balatro\Mods\Pokermon\Pokermon.

**Comment by scotthbk** [comment]
Thank you, I did what you advised and it works perfectly now.

**Comment by InertSteak** [comment]
Anytime!
