### ISSUE TITLE
Balatro suddenly crashing upon open

### ISSUE THREAD

**Issue by RandomNerd1** [InertSteak/Pokermon#58]
If I click during the intro where it shows an individual joker, or let it play out until it 'burns' away completely, my game freezes up.

I played for several sessions on 2.0.0a without issue, don't think anything's changed on my end. Any idea of the cause/fix?

**Comment by YamperAF** [comment]
You have a lot of mods?, that happen to me when i use modpacks

**Comment by RandomNerd1** [comment]
Only two other than Pokermon, these:

https://github.com/dvrp0/distro
https://github.com/Kooluve/Better-Mouse-And-Gamepad

I'll see if there's any difference with these mods off, but it would be strange because the successful sessions I mention in the OP had those on too, and like I said, I don't think anything changed since yesterday...

**Comment by RandomNerd1** [comment]
...welp, I don't know what to say, but I removed all but Pokermon, and no crash. Then I added one of the other mods above back, and no crash, then I added the other back too, so now I'm using all three again, and no crash, lol...

I have no idea what happened, but I guess I'm good now, lol... 🤔
