### ISSUE TITLE
Annihilape and Oddish don't stack?

### ISSUE THREAD

**Issue by zerosozha** [InertSteak/Pokermon#69]
I went with an all 7's build with Annihilape, then picked up an Oddish. Annihilape triggers but Oddish does not. Do these jokers not stack or is Oddish broken?

**Comment by InertSteak** [comment]
This is a visual issue, both work but oddish doesn't shake. Will be fixed

**Comment by InertSteak** [comment]
Just checked in a fix for this for oddish line and several other jokers
