### ISSUE TITLE
Ninetails

### ISSUE THREAD

**Issue by TheBearpig** [InertSteak/Pokermon#76]
Ninetails is missing its description. The box above Safari and Pokermon is empty.

**Comment by YamperAF** [comment]
what version you have?, are you playing in another lenguage is not english?

**Comment by TheBearpig** [comment]
I downloaded 2.0.0 today, playing in English.
Steammodded 1.0 alpha.

**Comment by InertSteak** [comment]
Yeah this is a known issue that was fixed. Try playing on the latest release, 2.0.0b or 2.0.0e.
