### ISSUE TITLE
Voltorb evolution doesn't progress if activated

### ISSUE THREAD

**Issue by klingbolt** [InertSteak/Pokermon#83]
When voltorb's ability activates it disables the joker until end of round. This is also disabling its evolution counter. Therefore it still says 3 rounds left even though it has been used twice. I doubt this is the intended behavior
![image](https://github.com/user-attachments/assets/145851a8-05e6-4745-b1d5-6f6063f87eb5)

**Comment by InertSteak** [comment]
Yes, debuffing removes all abilities, including its ability to level up. You have to conserve voltorb if you want it to evolve. This might be changed in the future, but it's intended for the time being.
